packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": true
  esbuild: true
  node-liblzma: true
  protobufjs: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - workerd
